### PR TITLE
Undo effects of sugar cereals on our youth

### PR DESCRIPTION
**Pull request by kfogel**

### CODE REVIEW

**Comment by slifty** [comment]
THANK YOU THIS IS GREAT

**Comment by erekalper** [comment]
image

**Comment by slifty** [comment]
Here's some context:
image

IT WAS A VALIANT ATTEMPT.

**Comment by kfogel** [comment]
So an error repeated for enough generations becomes law?

Pshaw, I say.  Pshaw!

**Comment by erekalper** [comment]
I done think that am yes.

**Comment by slifty** [comment]
IMPORTANT UPDATE: 

Fogel means bird in german.  @mstem thinks you have an eagle eye.

**Comment by slifty** [comment]
This motion has passed: no votes against, 4 votes yes.

**Comment by kfogel** [comment]
Thank you.

By the way, "Fogel" doesn't just mean bird in German, it also means bird in German in English!

**Pull request merged**
