### PR TITLE
Propose ridiculous compromise to the hyphens vs dashes debate

### PR DESCRIPTION
**Pull request by louh**
Please note that I make this pull request to enter it into the official corporate record but I do not endorse my own proposal on account of it being the worst idea I've ever had, and as a consequence hereby reject my own pull request.

### CODE REVIEW

**Comment by knowtheory** [comment]
i would like to propose an alternative which i've dubbed WaveCase, and the rule should be alternating capitals as well as underscores and hyphens as follows:

`many_word-PHRASE-gets_lower_and-HIGHER-as_we_go`

**Comment by slifty** [comment]
It seems like Ted's suggestion is getting more support.  @knowtheory would you be willing to open a PR?

**Comment by knowtheory** [comment]
Oh god.  This is that moment in a cult where you have to decide whether you're really in or not, isn't it.

**Comment by louh** [comment]
One day we will all be hauled before a war crimes tribunal and our only
defense would be "we all just kept going with it"

**Comment by slifty** [comment]
Hey @knowtheory just a reminder that this is still needed if you have a minute.

**Comment by slifty** [comment]
I'm going to close this PR for now since section-2 is a dead branch and we have a few other files in master now that will need this change applied.

**Comment by louh** [comment]
Oh thank god

**Pull request closed without merging**
